package com.example.myprept.responses

class ReposResponse {

    val succesfullResponse = "{\n" +
            "    \"total_count\": 1308357,\n" +
            "    \"incomplete_results\": false,\n" +
            "    \"items\": [\n" +
            "        {\n" +
            "            \"id\": 82128465,\n" +
            "            \"node_id\": \"MDEwOlJlcG9zaXRvcnk4MjEyODQ2NQ==\",\n" +
            "            \"name\": \"Android\",\n" +
            "            \"full_name\": \"open-android/Android\",\n" +
            "            \"private\": false,\n" +
            "            \"owner\": {\n" +
            "                \"login\": \"open-android\",\n" +
            "                \"id\": 23095877,\n" +
            "                \"node_id\": \"MDQ6VXNlcjIzMDk1ODc3\",\n" +
            "                \"avatar_url\": \"https://avatars.githubusercontent.com/u/23095877?v=4\",\n" +
            "                \"gravatar_id\": \"\",\n" +
            "                \"url\": \"https://api.github.com/users/open-android\",\n" +
            "                \"html_url\": \"https://github.com/open-android\",\n" +
            "                \"followers_url\": \"https://api.github.com/users/open-android/followers\",\n" +
            "                \"following_url\": \"https://api.github.com/users/open-android/following{/other_user}\",\n" +
            "                \"gists_url\": \"https://api.github.com/users/open-android/gists{/gist_id}\",\n" +
            "                \"starred_url\": \"https://api.github.com/users/open-android/starred{/owner}{/repo}\",\n" +
            "                \"subscriptions_url\": \"https://api.github.com/users/open-android/subscriptions\",\n" +
            "                \"organizations_url\": \"https://api.github.com/users/open-android/orgs\",\n" +
            "                \"repos_url\": \"https://api.github.com/users/open-android/repos\",\n" +
            "                \"events_url\": \"https://api.github.com/users/open-android/events{/privacy}\",\n" +
            "                \"received_events_url\": \"https://api.github.com/users/open-android/received_events\",\n" +
            "                \"type\": \"User\",\n" +
            "                \"site_admin\": false\n" +
            "            },\n" +
            "            \"html_url\": \"https://github.com/open-android/Android\",\n" +
            "            \"description\": \"GitHub上最火的Android开源项目,所有开源项目都有详细资料和配套视频\",\n" +
            "            \"fork\": false,\n" +
            "            \"url\": \"https://api.github.com/repos/open-android/Android\",\n" +
            "            \"forks_url\": \"https://api.github.com/repos/open-android/Android/forks\",\n" +
            "            \"keys_url\": \"https://api.github.com/repos/open-android/Android/keys{/key_id}\",\n" +
            "            \"collaborators_url\": \"https://api.github.com/repos/open-android/Android/collaborators{/collaborator}\",\n" +
            "            \"teams_url\": \"https://api.github.com/repos/open-android/Android/teams\",\n" +
            "            \"hooks_url\": \"https://api.github.com/repos/open-android/Android/hooks\",\n" +
            "            \"issue_events_url\": \"https://api.github.com/repos/open-android/Android/issues/events{/number}\",\n" +
            "            \"events_url\": \"https://api.github.com/repos/open-android/Android/events\",\n" +
            "            \"assignees_url\": \"https://api.github.com/repos/open-android/Android/assignees{/user}\",\n" +
            "            \"branches_url\": \"https://api.github.com/repos/open-android/Android/branches{/branch}\",\n" +
            "            \"tags_url\": \"https://api.github.com/repos/open-android/Android/tags\",\n" +
            "            \"blobs_url\": \"https://api.github.com/repos/open-android/Android/git/blobs{/sha}\",\n" +
            "            \"git_tags_url\": \"https://api.github.com/repos/open-android/Android/git/tags{/sha}\",\n" +
            "            \"git_refs_url\": \"https://api.github.com/repos/open-android/Android/git/refs{/sha}\",\n" +
            "            \"trees_url\": \"https://api.github.com/repos/open-android/Android/git/trees{/sha}\",\n" +
            "            \"statuses_url\": \"https://api.github.com/repos/open-android/Android/statuses/{sha}\",\n" +
            "            \"languages_url\": \"https://api.github.com/repos/open-android/Android/languages\",\n" +
            "            \"stargazers_url\": \"https://api.github.com/repos/open-android/Android/stargazers\",\n" +
            "            \"contributors_url\": \"https://api.github.com/repos/open-android/Android/contributors\",\n" +
            "            \"subscribers_url\": \"https://api.github.com/repos/open-android/Android/subscribers\",\n" +
            "            \"subscription_url\": \"https://api.github.com/repos/open-android/Android/subscription\",\n" +
            "            \"commits_url\": \"https://api.github.com/repos/open-android/Android/commits{/sha}\",\n" +
            "            \"git_commits_url\": \"https://api.github.com/repos/open-android/Android/git/commits{/sha}\",\n" +
            "            \"comments_url\": \"https://api.github.com/repos/open-android/Android/comments{/number}\",\n" +
            "            \"issue_comment_url\": \"https://api.github.com/repos/open-android/Android/issues/comments{/number}\",\n" +
            "            \"contents_url\": \"https://api.github.com/repos/open-android/Android/contents/{+path}\",\n" +
            "            \"compare_url\": \"https://api.github.com/repos/open-android/Android/compare/{base}...{head}\",\n" +
            "            \"merges_url\": \"https://api.github.com/repos/open-android/Android/merges\",\n" +
            "            \"archive_url\": \"https://api.github.com/repos/open-android/Android/{archive_format}{/ref}\",\n" +
            "            \"downloads_url\": \"https://api.github.com/repos/open-android/Android/downloads\",\n" +
            "            \"issues_url\": \"https://api.github.com/repos/open-android/Android/issues{/number}\",\n" +
            "            \"pulls_url\": \"https://api.github.com/repos/open-android/Android/pulls{/number}\",\n" +
            "            \"milestones_url\": \"https://api.github.com/repos/open-android/Android/milestones{/number}\",\n" +
            "            \"notifications_url\": \"https://api.github.com/repos/open-android/Android/notifications{?since,all,participating}\",\n" +
            "            \"labels_url\": \"https://api.github.com/repos/open-android/Android/labels{/name}\",\n" +
            "            \"releases_url\": \"https://api.github.com/repos/open-android/Android/releases{/id}\",\n" +
            "            \"deployments_url\": \"https://api.github.com/repos/open-android/Android/deployments\",\n" +
            "            \"created_at\": \"2017-02-16T02:10:13Z\",\n" +
            "            \"updated_at\": \"2022-06-02T18:15:46Z\",\n" +
            "            \"pushed_at\": \"2022-05-21T09:08:17Z\",\n" +
            "            \"git_url\": \"git://github.com/open-android/Android.git\",\n" +
            "            \"ssh_url\": \"git@github.com:open-android/Android.git\",\n" +
            "            \"clone_url\": \"https://github.com/open-android/Android.git\",\n" +
            "            \"svn_url\": \"https://github.com/open-android/Android\",\n" +
            "            \"homepage\": \"\",\n" +
            "            \"size\": 36,\n" +
            "            \"stargazers_count\": 12455,\n" +
            "            \"watchers_count\": 12455,\n" +
            "            \"language\": null,\n" +
            "            \"has_issues\": true,\n" +
            "            \"has_projects\": true,\n" +
            "            \"has_downloads\": true,\n" +
            "            \"has_wiki\": true,\n" +
            "            \"has_pages\": false,\n" +
            "            \"forks_count\": 3391,\n" +
            "            \"mirror_url\": null,\n" +
            "            \"archived\": false,\n" +
            "            \"disabled\": false,\n" +
            "            \"open_issues_count\": 52,\n" +
            "            \"license\": null,\n" +
            "            \"allow_forking\": true,\n" +
            "            \"is_template\": false,\n" +
            "            \"topics\": [\n" +
            "                \"android\",\n" +
            "                \"java\"\n" +
            "            ],\n" +
            "            \"visibility\": \"public\",\n" +
            "            \"forks\": 3391,\n" +
            "            \"open_issues\": 52,\n" +
            "            \"watchers\": 12455,\n" +
            "            \"default_branch\": \"master\",\n" +
            "            \"score\": 1.0\n" +
            "        },\n" +
            "        {\n" +
            "            \"id\": 12544093,\n" +
            "            \"node_id\": \"MDEwOlJlcG9zaXRvcnkxMjU0NDA5Mw==\",\n" +
            "            \"name\": \"Android\",\n" +
            "            \"full_name\": \"hmkcode/Android\",\n" +
            "            \"private\": false,\n" +
            "            \"owner\": {\n" +
            "                \"login\": \"hmkcode\",\n" +
            "                \"id\": 3790597,\n" +
            "                \"node_id\": \"MDQ6VXNlcjM3OTA1OTc=\",\n" +
            "                \"avatar_url\": \"https://avatars.githubusercontent.com/u/3790597?v=4\",\n" +
            "                \"gravatar_id\": \"\",\n" +
            "                \"url\": \"https://api.github.com/users/hmkcode\",\n" +
            "                \"html_url\": \"https://github.com/hmkcode\",\n" +
            "                \"followers_url\": \"https://api.github.com/users/hmkcode/followers\",\n" +
            "                \"following_url\": \"https://api.github.com/users/hmkcode/following{/other_user}\",\n" +
            "                \"gists_url\": \"https://api.github.com/users/hmkcode/gists{/gist_id}\",\n" +
            "                \"starred_url\": \"https://api.github.com/users/hmkcode/starred{/owner}{/repo}\",\n" +
            "                \"subscriptions_url\": \"https://api.github.com/users/hmkcode/subscriptions\",\n" +
            "                \"organizations_url\": \"https://api.github.com/users/hmkcode/orgs\",\n" +
            "                \"repos_url\": \"https://api.github.com/users/hmkcode/repos\",\n" +
            "                \"events_url\": \"https://api.github.com/users/hmkcode/events{/privacy}\",\n" +
            "                \"received_events_url\": \"https://api.github.com/users/hmkcode/received_events\",\n" +
            "                \"type\": \"User\",\n" +
            "                \"site_admin\": false\n" +
            "            },\n" +
            "            \"html_url\": \"https://github.com/hmkcode/Android\",\n" +
            "            \"description\": \"Android related examples\",\n" +
            "            \"fork\": false,\n" +
            "            \"url\": \"https://api.github.com/repos/hmkcode/Android\",\n" +
            "            \"forks_url\": \"https://api.github.com/repos/hmkcode/Android/forks\",\n" +
            "            \"keys_url\": \"https://api.github.com/repos/hmkcode/Android/keys{/key_id}\",\n" +
            "            \"collaborators_url\": \"https://api.github.com/repos/hmkcode/Android/collaborators{/collaborator}\",\n" +
            "            \"teams_url\": \"https://api.github.com/repos/hmkcode/Android/teams\",\n" +
            "            \"hooks_url\": \"https://api.github.com/repos/hmkcode/Android/hooks\",\n" +
            "            \"issue_events_url\": \"https://api.github.com/repos/hmkcode/Android/issues/events{/number}\",\n" +
            "            \"events_url\": \"https://api.github.com/repos/hmkcode/Android/events\",\n" +
            "            \"assignees_url\": \"https://api.github.com/repos/hmkcode/Android/assignees{/user}\",\n" +
            "            \"branches_url\": \"https://api.github.com/repos/hmkcode/Android/branches{/branch}\",\n" +
            "            \"tags_url\": \"https://api.github.com/repos/hmkcode/Android/tags\",\n" +
            "            \"blobs_url\": \"https://api.github.com/repos/hmkcode/Android/git/blobs{/sha}\",\n" +
            "            \"git_tags_url\": \"https://api.github.com/repos/hmkcode/Android/git/tags{/sha}\",\n" +
            "            \"git_refs_url\": \"https://api.github.com/repos/hmkcode/Android/git/refs{/sha}\",\n" +
            "            \"trees_url\": \"https://api.github.com/repos/hmkcode/Android/git/trees{/sha}\",\n" +
            "            \"statuses_url\": \"https://api.github.com/repos/hmkcode/Android/statuses/{sha}\",\n" +
            "            \"languages_url\": \"https://api.github.com/repos/hmkcode/Android/languages\",\n" +
            "            \"stargazers_url\": \"https://api.github.com/repos/hmkcode/Android/stargazers\",\n" +
            "            \"contributors_url\": \"https://api.github.com/repos/hmkcode/Android/contributors\",\n" +
            "            \"subscribers_url\": \"https://api.github.com/repos/hmkcode/Android/subscribers\",\n" +
            "            \"subscription_url\": \"https://api.github.com/repos/hmkcode/Android/subscription\",\n" +
            "            \"commits_url\": \"https://api.github.com/repos/hmkcode/Android/commits{/sha}\",\n" +
            "            \"git_commits_url\": \"https://api.github.com/repos/hmkcode/Android/git/commits{/sha}\",\n" +
            "            \"comments_url\": \"https://api.github.com/repos/hmkcode/Android/comments{/number}\",\n" +
            "            \"issue_comment_url\": \"https://api.github.com/repos/hmkcode/Android/issues/comments{/number}\",\n" +
            "            \"contents_url\": \"https://api.github.com/repos/hmkcode/Android/contents/{+path}\",\n" +
            "            \"compare_url\": \"https://api.github.com/repos/hmkcode/Android/compare/{base}...{head}\",\n" +
            "            \"merges_url\": \"https://api.github.com/repos/hmkcode/Android/merges\",\n" +
            "            \"archive_url\": \"https://api.github.com/repos/hmkcode/Android/{archive_format}{/ref}\",\n" +
            "            \"downloads_url\": \"https://api.github.com/repos/hmkcode/Android/downloads\",\n" +
            "            \"issues_url\": \"https://api.github.com/repos/hmkcode/Android/issues{/number}\",\n" +
            "            \"pulls_url\": \"https://api.github.com/repos/hmkcode/Android/pulls{/number}\",\n" +
            "            \"milestones_url\": \"https://api.github.com/repos/hmkcode/Android/milestones{/number}\",\n" +
            "            \"notifications_url\": \"https://api.github.com/repos/hmkcode/Android/notifications{?since,all,participating}\",\n" +
            "            \"labels_url\": \"https://api.github.com/repos/hmkcode/Android/labels{/name}\",\n" +
            "            \"releases_url\": \"https://api.github.com/repos/hmkcode/Android/releases{/id}\",\n" +
            "            \"deployments_url\": \"https://api.github.com/repos/hmkcode/Android/deployments\",\n" +
            "            \"created_at\": \"2013-09-02T16:12:28Z\",\n" +
            "            \"updated_at\": \"2022-06-02T03:07:12Z\",\n" +
            "            \"pushed_at\": \"2022-05-26T07:20:22Z\",\n" +
            "            \"git_url\": \"git://github.com/hmkcode/Android.git\",\n" +
            "            \"ssh_url\": \"git@github.com:hmkcode/Android.git\",\n" +
            "            \"clone_url\": \"https://github.com/hmkcode/Android.git\",\n" +
            "            \"svn_url\": \"https://github.com/hmkcode/Android\",\n" +
            "            \"homepage\": null,\n" +
            "            \"size\": 1842,\n" +
            "            \"stargazers_count\": 3285,\n" +
            "            \"watchers_count\": 3285,\n" +
            "            \"language\": \"Java\",\n" +
            "            \"has_issues\": true,\n" +
            "            \"has_projects\": true,\n" +
            "            \"has_downloads\": true,\n" +
            "            \"has_wiki\": true,\n" +
            "            \"has_pages\": false,\n" +
            "            \"forks_count\": 3429,\n" +
            "            \"mirror_url\": null,\n" +
            "            \"archived\": false,\n" +
            "            \"disabled\": false,\n" +
            "            \"open_issues_count\": 62,\n" +
            "            \"license\": null,\n" +
            "            \"allow_forking\": true,\n" +
            "            \"is_template\": false,\n" +
            "            \"topics\": [],\n" +
            "            \"visibility\": \"public\",\n" +
            "            \"forks\": 3429,\n" +
            "            \"open_issues\": 62,\n" +
            "            \"watchers\": 3285,\n" +
            "            \"default_branch\": \"master\",\n" +
            "            \"score\": 1.0\n" +
            "        },\n" +
            "        {\n" +
            "            \"id\": 5550567,\n" +
            "            \"node_id\": \"MDEwOlJlcG9zaXRvcnk1NTUwNTY3\",\n" +
            "            \"name\": \"android\",\n" +
            "            \"full_name\": \"owncloud/android\",\n" +
            "            \"private\": false,\n" +
            "            \"owner\": {\n" +
            "                \"login\": \"owncloud\",\n" +
            "                \"id\": 1645051,\n" +
            "                \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjE2NDUwNTE=\",\n" +
            "                \"avatar_url\": \"https://avatars.githubusercontent.com/u/1645051?v=4\",\n" +
            "                \"gravatar_id\": \"\",\n" +
            "                \"url\": \"https://api.github.com/users/owncloud\",\n" +
            "                \"html_url\": \"https://github.com/owncloud\",\n" +
            "                \"followers_url\": \"https://api.github.com/users/owncloud/followers\",\n" +
            "                \"following_url\": \"https://api.github.com/users/owncloud/following{/other_user}\",\n" +
            "                \"gists_url\": \"https://api.github.com/users/owncloud/gists{/gist_id}\",\n" +
            "                \"starred_url\": \"https://api.github.com/users/owncloud/starred{/owner}{/repo}\",\n" +
            "                \"subscriptions_url\": \"https://api.github.com/users/owncloud/subscriptions\",\n" +
            "                \"organizations_url\": \"https://api.github.com/users/owncloud/orgs\",\n" +
            "                \"repos_url\": \"https://api.github.com/users/owncloud/repos\",\n" +
            "                \"events_url\": \"https://api.github.com/users/owncloud/events{/privacy}\",\n" +
            "                \"received_events_url\": \"https://api.github.com/users/owncloud/received_events\",\n" +
            "                \"type\": \"Organization\",\n" +
            "                \"site_admin\": false\n" +
            "            },\n" +
            "            \"html_url\": \"https://github.com/owncloud/android\",\n" +
            "            \"description\": \":phone: The ownCloud Android App\",\n" +
            "            \"fork\": false,\n" +
            "            \"url\": \"https://api.github.com/repos/owncloud/android\",\n" +
            "            \"forks_url\": \"https://api.github.com/repos/owncloud/android/forks\",\n" +
            "            \"keys_url\": \"https://api.github.com/repos/owncloud/android/keys{/key_id}\",\n" +
            "            \"collaborators_url\": \"https://api.github.com/repos/owncloud/android/collaborators{/collaborator}\",\n" +
            "            \"teams_url\": \"https://api.github.com/repos/owncloud/android/teams\",\n" +
            "            \"hooks_url\": \"https://api.github.com/repos/owncloud/android/hooks\",\n" +
            "            \"issue_events_url\": \"https://api.github.com/repos/owncloud/android/issues/events{/number}\",\n" +
            "            \"events_url\": \"https://api.github.com/repos/owncloud/android/events\",\n" +
            "            \"assignees_url\": \"https://api.github.com/repos/owncloud/android/assignees{/user}\",\n" +
            "            \"branches_url\": \"https://api.github.com/repos/owncloud/android/branches{/branch}\",\n" +
            "            \"tags_url\": \"https://api.github.com/repos/owncloud/android/tags\",\n" +
            "            \"blobs_url\": \"https://api.github.com/repos/owncloud/android/git/blobs{/sha}\",\n" +
            "            \"git_tags_url\": \"https://api.github.com/repos/owncloud/android/git/tags{/sha}\",\n" +
            "            \"git_refs_url\": \"https://api.github.com/repos/owncloud/android/git/refs{/sha}\",\n" +
            "            \"trees_url\": \"https://api.github.com/repos/owncloud/android/git/trees{/sha}\",\n" +
            "            \"statuses_url\": \"https://api.github.com/repos/owncloud/android/statuses/{sha}\",\n" +
            "            \"languages_url\": \"https://api.github.com/repos/owncloud/android/languages\",\n" +
            "            \"stargazers_url\": \"https://api.github.com/repos/owncloud/android/stargazers\",\n" +
            "            \"contributors_url\": \"https://api.github.com/repos/owncloud/android/contributors\",\n" +
            "            \"subscribers_url\": \"https://api.github.com/repos/owncloud/android/subscribers\",\n" +
            "            \"subscription_url\": \"https://api.github.com/repos/owncloud/android/subscription\",\n" +
            "            \"commits_url\": \"https://api.github.com/repos/owncloud/android/commits{/sha}\",\n" +
            "            \"git_commits_url\": \"https://api.github.com/repos/owncloud/android/git/commits{/sha}\",\n" +
            "            \"comments_url\": \"https://api.github.com/repos/owncloud/android/comments{/number}\",\n" +
            "            \"issue_comment_url\": \"https://api.github.com/repos/owncloud/android/issues/comments{/number}\",\n" +
            "            \"contents_url\": \"https://api.github.com/repos/owncloud/android/contents/{+path}\",\n" +
            "            \"compare_url\": \"https://api.github.com/repos/owncloud/android/compare/{base}...{head}\",\n" +
            "            \"merges_url\": \"https://api.github.com/repos/owncloud/android/merges\",\n" +
            "            \"archive_url\": \"https://api.github.com/repos/owncloud/android/{archive_format}{/ref}\",\n" +
            "            \"downloads_url\": \"https://api.github.com/repos/owncloud/android/downloads\",\n" +
            "            \"issues_url\": \"https://api.github.com/repos/owncloud/android/issues{/number}\",\n" +
            "            \"pulls_url\": \"https://api.github.com/repos/owncloud/android/pulls{/number}\",\n" +
            "            \"milestones_url\": \"https://api.github.com/repos/owncloud/android/milestones{/number}\",\n" +
            "            \"notifications_url\": \"https://api.github.com/repos/owncloud/android/notifications{?since,all,participating}\",\n" +
            "            \"labels_url\": \"https://api.github.com/repos/owncloud/android/labels{/name}\",\n" +
            "            \"releases_url\": \"https://api.github.com/repos/owncloud/android/releases{/id}\",\n" +
            "            \"deployments_url\": \"https://api.github.com/repos/owncloud/android/deployments\",\n" +
            "            \"created_at\": \"2012-08-25T10:35:56Z\",\n" +
            "            \"updated_at\": \"2022-06-02T13:18:17Z\",\n" +
            "            \"pushed_at\": \"2022-06-03T09:16:46Z\",\n" +
            "            \"git_url\": \"git://github.com/owncloud/android.git\",\n" +
            "            \"ssh_url\": \"git@github.com:owncloud/android.git\",\n" +
            "            \"clone_url\": \"https://github.com/owncloud/android.git\",\n" +
            "            \"svn_url\": \"https://github.com/owncloud/android\",\n" +
            "            \"homepage\": \"\",\n" +
            "            \"size\": 245018,\n" +
            "            \"stargazers_count\": 3319,\n" +
            "            \"watchers_count\": 3319,\n" +
            "            \"language\": \"Kotlin\",\n" +
            "            \"has_issues\": true,\n" +
            "            \"has_projects\": true,\n" +
            "            \"has_downloads\": true,\n" +
            "            \"has_wiki\": false,\n" +
            "            \"has_pages\": false,\n" +
            "            \"forks_count\": 2965,\n" +
            "            \"mirror_url\": null,\n" +
            "            \"archived\": false,\n" +
            "            \"disabled\": false,\n" +
            "            \"open_issues_count\": 274,\n" +
            "            \"license\": {\n" +
            "                \"key\": \"gpl-2.0\",\n" +
            "                \"name\": \"GNU General Public License v2.0\",\n" +
            "                \"spdx_id\": \"GPL-2.0\",\n" +
            "                \"url\": \"https://api.github.com/licenses/gpl-2.0\",\n" +
            "                \"node_id\": \"MDc6TGljZW5zZTg=\"\n" +
            "            },\n" +
            "            \"allow_forking\": true,\n" +
            "            \"is_template\": false,\n" +
            "            \"topics\": [\n" +
            "                \"android\",\n" +
            "                \"kotlin\",\n" +
            "                \"owncloud\"\n" +
            "            ],\n" +
            "            \"visibility\": \"public\",\n" +
            "            \"forks\": 2965,\n" +
            "            \"open_issues\": 274,\n" +
            "            \"watchers\": 3319,\n" +
            "            \"default_branch\": \"master\",\n" +
            "            \"score\": 1.0\n" +
            "        }\n" +
            "    ]\n" +
            "}"
}